### PR TITLE
Git sub modules handle 

### PR DESCRIPTION
**Pull request by melezhik**
I guess this is way to go, however git sub modules still get checkout in wrong (?) location ? https://ci.sparrowhub.io/report/3043 

Feel free to disregard it , as this is just an idea …

### CODE REVIEW

**Comment by rawleyfowler** [comment]
Hmm, I am trying to use CMake to handle this on install but not sure if it is working on sparrow. It works on github CI if you want to see @melezhik https://github.com/rawleyfowler/JSON-Simd/actions

**Comment by melezhik** [comment]
@rawleyfowler  I mean Git submodules are checked out - 

```
03:30:26 :: Submodule path 'cc/lib/simdjson': checked out '22cc523fd4e2fd6d4a941cd41662e251f241b2dc' 
```

however they probably are checkout in a location where zef test does not expect them?


```
03:30:31 :: ===> Testing: JSON-Simd:ver<0.0.1>:auth<zef:rawleyfowler>
03:30:33 :: [JSON-Simd] ===SORRY!=== Error while compiling /var/.sparrowdo/env/test/.sparrowdo/source/t/00-use.rakutest
03:30:33 :: [JSON-Simd] Cannot locate native library '/var/.sparrowdo/env/test/.sparrowdo/source/resources/libraries/libsimd-json.so': /var/.sparrowdo/env/test/.sparrowdo/source/resources/libraries/libsimd-json.so: cannot open shared object file: No such file or directory
03:30:33 :: [JSON-Simd] at /var/.sparrowdo/env/test/.sparrowdo/source/t/00-use.rakutest:7
03:30:33 :: [JSON-Simd] t/00-use.rakutest .. 
03:30:33 :: [JSON-Simd] Dubious, test returned 1 (wstat 256, 0x100)
03:30:33 :: [JSON-Simd] No subtests run 
03:30:33 :: [JSON-Simd] Test Summary Report
```

**Comment by rawleyfowler** [comment]
I am expecting the files to be in `cc/lib/simdjson` simdjson is the submodule.

**Comment by melezhik** [comment]
the latest commit in this PR fixes the issue - https://ci.sparrowhub.io/report/3045 ))) we forgot to do `zef build .` ))

**Comment by melezhik** [comment]
> Hmm, I am trying to use CMake to handle this on install but not sure if it is working on sparrow. It works on github CI if you want to see

so, if cmake takes care about checking out of submodule, I wonder if need this step explicitly done in sparrowci pipeline?  🤔 

https://github.com/melezhik/JSON-Simd/blob/8fd116763e588e0a6bd573642867971e1b974897/sparrow.yaml#L11-L12

**Comment by rawleyfowler** [comment]
@melezhik Yeah we don't need those lines anymore. Can you test without it?

**Comment by melezhik** [comment]
> @melezhik Yeah we don't need those lines anymore. Can you test without it?

It works without those lines - https://ci.sparrowhub.io/report/3046

**Comment by rawleyfowler** [comment]
Thanks @melezhik

**Comment by melezhik** [comment]
Cool!

**Pull request merged**
